blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/aacitelli/typescript-serverless-monorepo-template/discussions/new
    about: Ask questions and discuss with other community members